- title: Beacon
  url: https://beacon.support/
  caption: Helping local public service partners understand and support the needs of their communities 

- title: Coronavirus support service directory
  url: https://github.com/wearefuturegov/coronavirus-service-directory
  caption: Find the open source code for the directory
  
- title: Camden Council coronavirus help directory
  url: https://coronavirus-help.camden.gov.uk/
  caption: Visit Camden's live directory
  
- title: Buckinghamshire Council coronavirus help directory
  url: https://directory.buckinghamshire.gov.uk/
  caption: Visit Buckinghamshire's live directory

- title: Open Project System (OPS)
  url: https://github.com/GreaterLondonAuthority/GLA-OPS
  caption: An open source grant and project management system from Greater London Authority which organisations can use to submit bids for funding.

- title: Hackney Council Find support services map
  url: https://hackney.gov.uk/find-support-services
  caption: This map provides details of voluntary and community organisations that are offering help to people affected by coronavirus and lockdown.
